language: c

sudo: false
cache:
  directories:
  - $HOME/.stack/

matrix:
  include:
    - env: CABALVER=1.22 GHCVER=7.10.3
      addons:
      addons:
        apt:
          sources:
          - hvr-ghc
          packages:
          - ghc-7.10.3
          - caval-install-1.22

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar -xzO --wildcards '*/stack' > ~/.local/bin/stack
  - chmod a+x ~/.local/bin/stack
  - stack config set system-ghc --global true
  - export PATH=/opt/ghc/7.10.3/bin:~/.local/bin/stack:$PATH


script:
  - bash test.sh
